- name: Install httpd
  hosts: all

  tasks:
  - name: Install httpd package on Ubuntu hosts
    apt:
     name: apache2
     state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Make sure a service is running
    systemd:
      state: started
      enabled: yes
      name: apache2
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Stop and disable ufw
    systemd:
      state: stopped
      enabled: no
      name: ufw
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install httpd package on Fedora or CentOS hosts
    dnf:
     name: httpd
     state: present
    when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'
  - name: Make sure a service is running
    systemd:
      state: started
      enabled: yes
      name: httpd
    when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'
  - name: Stop and disable ufw
    systemd:
      state: stopped
      enabled: no
      name: firewalld
    when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'

  - name: Copy file with owner and permissions
    copy:
      src: ./materials/index.html
      dest: /var/www/html/index.html
      mode: '0755'